[package]
name = "patterns"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
react-rs-core = { path = "../../crates/react-core" }
react-rs-elements = { path = "../../crates/react-elements" }
